Repository code4moldova/voluntar-backend, pull requests merged in 2020-10, with the labels that each got.

#103 doc update and gitignore addition for vscode
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: documentation

#101 Vb 2 get volunteers by filter
  backend/endpoints/volunteer.py
  backend/models/volunteer_model.py
  backend/seeds.py
  backend/static/swagger.yaml
  backend/utils/search.py
Labels: enhancement

#113 Replace json.loads with clean_data
  backend/endpoints/beneficiary.py
  backend/endpoints/volunteer.py
  backend/models/beneficiary_model.py
  backend/models/volunteer_model.py
Labels: bug

#109 Changes for beneficiary admin pages
  .github/workflows/pythonapp.yml
  backend/app.py
  backend/endpoints/beneficiary.py
  backend/endpoints/requests.py
  backend/endpoints/volunteer.py
  backend/models/__init__.py
  backend/models/beneficiary_model.py
  backend/models/cluster_model.py
  backend/models/enums.py
  backend/models/request_model.py
  backend/models/user_model.py
  backend/models/volunteer_model.py
  backend/seeds.py
  backend/server.py
  backend/services/request_service.py
  backend/tests/__init__.py
  backend/tests/endpoints/test_requests.py
  backend/tests/factories.py
  backend/tests/services/test_table_list.py
  backend/tests/unit/test_operator.py
Labels: enhancement

#104 #94 create user request
  backend/app.py
  backend/endpoints/__init__.py
  backend/endpoints/user_request.py
  backend/static/swagger.yaml
Labels: hacktoberfest

#111 Vb 3
  backend/endpoints/operator.py
  backend/models/user_model.py
  backend/static/swagger.yaml
Labels: enhancement

#119 Vb 15 add endpoint for creating a new notification
  backend/app.py
  backend/endpoints/__init__.py
  backend/endpoints/notification.py
  backend/models/__init__.py
  backend/models/notifcation_user_model.py
  backend/models/notification_model.py
  backend/seeds.py
  backend/static/swagger.yaml
  backend/tests/factories.py
Labels: enhancement

#121 Add new endpoint to get a request by ID
  backend/app.py
  backend/endpoints/requests.py
  backend/models/request_model.py
Labels: enhancement

#127 Vb20 filter the beneficiary using phone and landline
  backend/endpoints/beneficiary.py
  backend/seeds.py
  backend/static/swagger.yaml
Labels: enhancement

#123 Add filter requests by type
  backend/services/request_service.py
Labels: enhancement
